version: "3"
services:
  app:
    image: douglas/zf2
    build: ./.docker
    container_name: doug-app
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:80"
    networks:
      - doug-network
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: doug-db
    command: --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp=1
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: doug_db
    networks:
      - doug-network
    volumes:
      - ./.docker/data/mysql:/var/lib/mysql
  
  phpmyadmin:
    container_name: doug-phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - doug-network

networks:
  doug-network:
    driver: bridge
